version: "3.5"
services:
  mongodb:
    # build: ./mongodb
    image: mongo:5.0.8
    container_name: phramTrace-mongo
    command: mongod --auth
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_PASSWORD: pharmaTrace
      MONGO_INITDB_ROOT_USERNAME: pharmaTrace
      MONGO_INITDB_DATABASE: admin
      MONGO_USERNAME: pharmaTrace
      MONGO_PASSWORD: pharmaTrace
      MONGO_DATABASE: pharmaTrace
    volumes:
     - /etc/localtime:/etc/localtime
     - ./data/db:/data/db      


# mongo admin -u pharmaTrace -p pharmaTrace
